# Generated by Django 6.0.1 on 2026-02-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_teacherrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, help_text='User Mobile Number', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='roll_no',
            field=models.CharField(blank=True, help_text='Student Roll Number', max_length=50, null=True),
        ),
    ]
