# Generated by Django 6.0.1 on 2026-03-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_mobile_user_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='principalrequest',
            name='college_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='principalrequest',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='college_logos/'),
        ),
        migrations.AddField(
            model_name='principalrequest',
            name='selected_plan',
            field=models.CharField(blank=True, choices=[('single', 'Single Experiment Plan (₹1,000)'), ('dpharm', 'D.Pharm Plan (₹11,999)'), ('combo', 'D.Pharm + B.Pharm Plan (₹19,999)')], max_length=50, null=True),
        ),
    ]
