# Generated by Django 6.0.1 on 2026-03-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_principalrequest_college_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='college_logos/'),
        ),
    ]
