# Generated by Django 6.0.1 on 2026-03-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_college_address_college_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='selected_plan',
            field=models.CharField(choices=[('single', 'Single Experiment Plan (₹1,000)'), ('dpharm', 'D.Pharm Plan (₹11,999)'), ('combo', 'D.Pharm + B.Pharm Plan (₹19,999)')], default='combo', max_length=50),
        ),
    ]
