# Generated by Django 6.0.1 on 2026-03-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherrequest',
            name='subject',
            field=models.CharField(blank=True, choices=[('dpharm_2', 'SECOND YEAR D.PHARM: PHARMACOLOGY'), ('bpharm_4', 'SECOND YEAR B. PHARM ( SEM-IV) : PHARMACOLOGY-I'), ('bpharm_5', 'THIRD YEAR B.PHARM(SEM-V): PHARMACOLOGY-II'), ('bpharm_6', 'THIRD YEAR B.PHARM (SEM-VI) : PHARMACOLOGY-III')], max_length=100, null=True),
        ),
    ]
