# Generated by Django 6.0.1 on 2026-03-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_teacherrequest_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherrequest',
            name='subject',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='subject',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
