# Generated by Django 6.0.1 on 2026-03-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_teacherrequest_subject_alter_user_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
