# Generated by Django 6.0.1 on 2026-05-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_college_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prn_no',
            field=models.CharField(blank=True, help_text='Student PRN Number', max_length=50, null=True),
        ),
    ]
